"$schema" = 'https://starship.rs/config-schema.json'

format = """$directory\
            $git_branch\
            $git_commit\
            $git_status\
            $cmd_duration\
            $fill\
            $c\
            $lua\
            $nodejs\
            $python\
            ${env_var.STARSHIP_VENV_PROMPT}\
            $line_break\
            $battery\
            $character\
            """

[line_break]
disabled = false

[fill]
symbol = " "

[directory] 
truncation_length = 0

[git_branch]
symbol = " "

[docker_context]
symbol = " "

#### programming languages ####
[c]
symbol = " "

[lua]
symbol = "󰢱 "
format = ' [$symbol($version )]($style)'

[nodejs]
symbol = " "
format = ' [$symbol($version )]($style)'

[python]
symbol = " "
format = ' [${symbol}${pyenv_prefix}(${version} )]($style)'

# this is for correct python env var display
[env_var.STARSHIP_VENV_PROMPT]
format = '[\($env_value\)]($style)'
style = "yellow bold"

[scala]
symbol = " "
format = ' [${symbol}(${version} )]($style)'

#### keep these below. Maybe I want to extend
#
#[rust]
#symbol = " "
#
#[golang]
#symbol = " "
#
#[php]
#symbol = " "
#
#[java]
#symbol = " "
#
#[kotlin]
#symbol = " "
#
#[haskell]
#symbol = " "
#

